### ISSUE TITLE
Maintain Choice when Window Resized

### ISSUE THREAD

**Issue by stefanopagliari** [gquental/obsidian-window-collapse#1]
Thank you for this very helpful plugin the that has become part of my workflow.

Currently when the Obsidian window is resized or the font size is changed, the sidebars re-appears and they need to be hidden again. Is there a way to avoid this?

Thank you

S.

**Comment by gquental** [comment]
Hi Stefano, thank you so much for your feedback!

I tried to reproduce the issue that you mentioned, both by resizing or changing the font size and wasn't able to do it.
Just wondering, do you have another plugin that handles the sidebar as well?

If not, can you share a little `gif` of the issue?

Thx

**Comment by stefanopagliari** [comment]
Hi. You were completely right. The behaviour was due to the "hide sidebars when narrow". plugin (https://github.com/mybuddymichael/obsidian-hide-sidebars-when-narrow). This automatically hide the sidebar when the window is resize, but I did not realise that it also brought them back once then window becomes large again.
